### ISSUE TITLE
Forget password does not sent email

### ISSUE THREAD

**Issue by r42998** [BruceBuckland/signin#1]
Hello,

it does not seem that the forget password sends an email. When entering a valid user name and clicking on "Forgot password" I get an error:

2016-08-21 14:33:58.702 signin[3060:54612] Could not load the "img8" image referenced from a nib in the bundle with identifier "com.odellventures.signin"
I then changed the image reference of the image view but then get:

2016-08-21 14:34:15.656 signin[3060:54849] AWSiOSSDK v2.4.7 [Debug] AWSURLResponseSerialization.m line:63 | -[AWSJSONResponseSerializer responseObjectForResponse:originalRequest:currentRequest:data:error:] | Response body:
{"CodeDeliveryDetails":{"AttributeName":"email","DeliveryMedium":"Email","Destination":"q***@h***.com"}}

Thanks,
Fred

**Comment by BruceBuckland** [comment]
Sorry Fred.  The Storyboard still refers to img8 (I reduced the number of images and didn't fix the storyboard) Will push a change.

**Comment by BruceBuckland** [comment]
As far as the image problem (img8) is fixed now and committed on github, ( or you can just find img8 in xcode and change them all to img1).  This resulted in the background image not cycling while you were changing password.

As far as the log entry is concerned:  I suspect that it still functioned, I suspect that it did email you the code at q@h.com <mailto:q@h.com>.   You must use a real email address in the registration in order to have the email send a confirmation code (I did not implement text message confirmation or changing email addresses).  Here is a copy of a normal log entry for forgot password processing.  Following this message I get an email with a confirmation code at an address (which AWS blanks out in the log).:

Hope it  works out for you , thanks for downloading it, let me know if you have trouble

bruce

Response body:
{"CodeDeliveryDetails":{"AttributeName":"email","DeliveryMedium":"Email","Destination":"o***@o***.com”}}

**Comment by r42998** [comment]
Thanks Bruce for your fix.
The email address I use is a real one as this is what is used for the registration process which was successful. For some reason, the obfuscation did not show up properly in the log but the wildcards are there as well (q***@h***.com).
I will check if their anything I need to change in the Cognito settings and will report back if I find anything there as from the log, it may be something wrong more from the server side.
I have include more details of the log just masking some of the keys/ids. Note that I am one iOS9.3
 
2016-08-22 08:31:04.568 signin[3512:120935] AWSiOSSDK v2.4.7 [Debug] AWSURLSessionManager.m line:526 | -[AWSURLSessionManager printHTTPHeadersAndBodyForRequest:] | Request headers:
{
    "Content-Type" = "application/x-amz-json-1.1";
    Host = "cognito-idp.us-west-2.amazonaws.com";
    "User-Agent" = "aws-sdk-iOS/2.4.7 iPhone-OS/9.3 en_US";
    "X-Amz-Date" = 20160822T123104Z;
    "X-Amz-Target" = "AWSCognitoIdentityProviderService.ForgotPassword";
}
2016-08-22 08:31:04.568 signin[3512:120935] AWSiOSSDK v2.4.7 [Debug] AWSURLSessionManager.m line:543 | -[AWSURLSessionManager printHTTPHeadersAndBodyForRequest:] | Request body:
{"SecretHash":"h+**************************************88=","ClientId":"******************","Username":"test1234"}
2016-08-22 08:31:05.412 signin[3512:121079] AWSiOSSDK v2.4.7 [Debug] AWSURLSessionManager.m line:553 | -[AWSURLSessionManager printHTTPHeadersForResponse:] | Response headers:
{
    Connection = "keep-alive";
    "Content-Length" = 104;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "Mon, 22 Aug 2016 12:30:51 GMT";
    "x-amzn-RequestId" = "43*****a7-6*****4-1****-9****1-7b*******8";
}
2016-08-22 08:31:05.413 signin[3512:121079] AWSiOSSDK v2.4.7 [Debug] AWSURLResponseSerialization.m line:63 | -[AWSJSONResponseSerializer responseObjectForResponse:originalRequest:currentRequest:data:error:] | Response body:
{"CodeDeliveryDetails":{"AttributeName":"email","DeliveryMedium":"Email","Destination":"q***@h***.com"}}

**Comment by BruceBuckland** [comment]
Thanks fred.  Note that the log entries seem to be verbose (even though the code in appDelegate does not turn on verbose logging.  Don't know why that is (ask AWS I guess) ... but I suspect if you do a non-debug build it will log less (I have never tried... this code was just to answer a question on stackexchange.)

**Comment by BruceBuckland** [comment]
@r42998 I have abandoned this version (signin) and used a different approach in SignIn-awsmhh.  The new approach uses aws-mobile-hub-helper libraries to communicate with Cognito.  This approach really simplifies dealing with identities in an unauthenticated or authenticated state. See: [SignIn-awsmhh](https://github.com/BruceBuckland/SignIn-awsmhh). This version also supports unauth, auth, google, facebook and CognitoYourUserPools (AWSCognitoIdentityUserPool)
